## Creating the array in numpy

In [7]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

### Creatingg 2D array


In [9]:
arr_2d = np.array([[1,3,4],[2,4,5]])
arr_2d

array([[1, 3, 4],
       [2, 4, 5]])

In [10]:
# Array of zeros
zeros_arr = np.zeros(4)
print(zeros_arr)
zeors_arr_2d = np.zeros((2,3))
print(zeors_arr_2d)

# Array of ones
ones_arr = np.ones(4)
print(ones_arr)
ones_arr_2d = np.ones((2,3))
print(ones_arr_2d)

# With range values
range_arr = np.arange(0,12)
print(range_arr)

# Random array
random_arr = np.random.random(12)
print(random_arr)

# evenly spaced number over interval
linspace_arr = np.linspace(0, 10, 5)
print(linspace_arr)


[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0.0786759  0.00820879 0.5730724  0.20090682 0.61231095 0.2245791
 0.35369699 0.97859022 0.35440423 0.63767482 0.25449498 0.67736957]
[ 0.   2.5  5.   7.5 10. ]


### Array properties and attributes

In [11]:
new_arr = np.array([[12,13,14],[15,16,17]])
print(new_arr)

#dimension of array
print(new_arr.ndim)

#shape of array
print(new_arr.shape)

#total size
print(new_arr.size)

#size in bytes of each elemen
print(new_arr.itemsize)

#transpose of array
print(new_arr.T)

[[12 13 14]
 [15 16 17]]
2
(2, 3)
6
8
[[12 15]
 [13 16]
 [14 17]]


### Operations on Array

In [12]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# Addition
print(a+b)

#Subtraction
print(a-b)

#multiplication element wise
print(a*b)

# division of array 
print(a/b)

#Exponention
print(a ** 2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]


### Comparison Operators


In [ ]:
my_fav = np.array([12,3,4,5])
print(my_fav > 2)
print(my_fav == 2)


[ True  True  True  True]
[False False False False]


### Aggeration Functions

In [15]:
print(np.min(my_fav))
print(np.max(my_fav))
print(np.median(my_fav))
print(np.std(my_fav))
print(np.mean(my_fav))


3
12
4.5
3.5355339059327378
6.0
