## Creating the array in numpy

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
arr

### Creatingg 2D array


In [ ]:
arr_2d = np.array([[1,3,4],[2,4,5]])
arr_2d

In [ ]:
# Array of zeros
zeros_arr = np.zeros(4)
print(zeros_arr)
zeors_arr_2d = np.zeros((2,3))
print(zeors_arr_2d)

# Array of ones
ones_arr = np.ones(4)
print(ones_arr)
ones_arr_2d = np.ones((2,3))
print(ones_arr_2d)

# With range values
range_arr = np.arange(0,12)
print(range_arr)

# Random array
random_arr = np.random.random(12)
print(random_arr)

# evenly spaced number over interval
linspace_arr = np.linspace(0, 10, 5)
print(linspace_arr)


### Array properties and attributes

In [ ]:
new_arr = np.array([[12,13,14],[15,16,17]])
print(new_arr)

#dimension of array
print(new_arr.ndim)

#shape of array
print(new_arr.shape)

#total size
print(new_arr.size)

#size in bytes of each elemen
print(new_arr.itemsize)

#transpose of array
print(new_arr.T)

### Operations on Array

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# Addition
print(a+b)

#Subtraction
print(a-b)

#multiplication element wise
print(a*b)

# division of array 
print(a/b)

#Exponention
print(a ** 2)

### Comparison Operators


In [ ]:
my_fav = np.array([12,3,4,5])
print(my_fav > 2)
print(my_fav == 2)


### Aggeration Functions

In [ ]:
print(np.min(my_fav))
print(np.max(my_fav))
print(np.median(my_fav))
print(np.std(my_fav))
print(np.mean(my_fav))


### Dot Product

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# [
#     (1*5)+(2*7)     (1*6)+(2*8)
#     (3*5)+(4*7)     (3*6)+(4*8)
# ]

print(np.dot(a, b))

### BroadCasting (automatically expands dimensions)

In [ ]:
a = np.array([1, 2, 3])
b = 2

print(a + b)

### Reshaping Arrays


In [23]:
my_arr = np.array([1,2,3,4,5,6])
reshaped_2d = my_arr.reshape(2,3)
print(reshaped_2d)

# Flatten array method 1
flatten_arr = reshaped_2d.reshape(-1)
print(flatten_arr)

# Method 2
my_arr = np.array([1,2,3,4,5,6])
reshaped_2d = my_arr.reshape(2,3)
print(reshaped_2d)

# This method returns copy of array
flatten_arr = reshaped_2d.flatten()
print(flatten_arr)

my_arr = np.array([1,2,3,4,5,6])
reshaped_2d = my_arr.reshape(2,3)
print(reshaped_2d)

# returns view instead of copy
reval_arr = reshaped_2d.ravel()
print(reval_arr)




[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


### Split array into equal size

In [21]:
arr = np.arange(10)
split_arr = np.split(arr, 2)
print(split_arr)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
