## Creating the array in numpy

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

### Creatingg 2D array


In [5]:
arr_2d = np.array([[1,3,4],[2,4,5]])
arr_2d

array([[1, 3, 4],
       [2, 4, 5]])

In [ ]:
# Array of zeros
zeros_arr = np.zeros(4)
print(zeros_arr)
zeors_arr_2d = np.zeros((2,3))
print(zeors_arr_2d)

# Array of ones
ones_arr = np.ones(4)
print(ones_arr)
ones_arr_2d = np.ones((2,3))
print(ones_arr_2d)

# With range values
range_arr = np.arange(0,12)
print(range_arr)

# Random array
random_arr = np.random.random(12)
print(random_arr)

# evenly spaced number over interval
linspace_arr = np.linspace(0, 10, 5)
print(linspace_arr)


[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0.18580906 0.487543   0.0836689  0.94937829 0.38322039 0.71769417
 0.49429854 0.48915992 0.6773421  0.91172189 0.24178184 0.64867247]
[ 1.    3.25  5.5   7.75 10.  ]


### Array properties and attributes

In [20]:
new_arr = np.array([[12,13,14],[15,16,17]])
print(new_arr)

#dimension of array
print(new_arr.ndim)

#shape of array
print(new_arr.shape)

#total size
print(new_arr.size)

#size in bytes of each elemen
print(new_arr.itemsize)

#transpose of array
print(new_arr.T)

[[12 13 14]
 [15 16 17]]
2
(2, 3)
6
8
[[12 15]
 [13 16]
 [14 17]]


### Operations on Array

In [24]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# Addition
print(a+b)

#Subtraction
print(a-b)

#multiplication element wise
print(a*b)

# division of array 
print(a/b)

#Exponention
print(a ** 2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]
