In [ ]:
import numpy as np

### 🔍 Array Indexing

In [ ]:
arr = np.array([2,4,6,8,10])

print('Simple Indexing ', arr[2])
print('Negative Indexing ', arr[-1])
print('Range Indexing ', arr[1:4])

arr_2d = np.array(
   [ [11,12,13,14],
    [15,16,17,18],
    [19,20,21,22],]
)

print('Specific Element 2D ', arr_2d[1,2])
print('Entrie row ', arr_2d[1])
print('Entrie Column ', arr_2d[:,1])

### ✂️ Slicing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print('Simple Slicing',arr[1:4])

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print('Slicing in 2D array ', arr_2d[:, 1:]) 

### 🔢 Sorting Arrays



In [16]:
arr = np.array([5,3,21,7,2])

print("Sorted array ", np.sort(arr))

arr_2d = np.array([[9,3,1], [7,2,1],[6,3,2]])
print('Sort row-wise ', np.sort(arr_2d, axis=1))
print('Sort column-wise ', np.sort(arr_2d, axis=0))

Sorted array  [ 2  3  5  7 21]
Sort row-wise  [[1 3 9]
 [1 2 7]
 [2 3 6]]
Sort column-wise  [[6 2 1]
 [7 3 1]
 [9 3 2]]


### ▼ Filtering

In [ ]:
arr = np.array([1,2,3,2,5,8,4])

print('Simple filter', arr[arr > 4])

# using mask
mask = arr > 4
print('By Mask method ', arr[mask])

Simple filter [5 8]
By Mask method  [5 8]


### ✔ Filtering by Where Caluse 

In [ ]:
arr = np.array([1,2,3,2,5,8,4])
result = np.where(arr > 4)
print('Where Clause Result ', result)
print('Array Result ', arr[result])



Where Clause Result  (array([4, 5]),)
Array Result  [5 8]


### 💫 Fancy Indexing

In [22]:
arr = np.array([10, 20, 30, 40])
indices = [0, 2]
print(arr[indices])

arr2d = np.array([[1, 2], [3, 4]])
print(arr2d[[0, 1], [1, 0]])

[10 30]
[2 3]


### ➕ Adding New Row / Column

In [24]:
arr = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
arr = np.vstack((arr, new_row))
print('Adding a new row', arr)

new_col = np.array([[7], [8], [9]])
arr = np.hstack((arr, new_col))
print('Adding a new column', arr)


Adding a new row [[1 2]
 [3 4]
 [5 6]]
Adding a new column [[1 2 7]
 [3 4 8]
 [5 6 9]]


### ➖ Deleting Data (row/column/entry)

In [27]:
arr = np.array([10, 20, 30, 40])
arr = np.delete(arr, 1)  
print('Deleting only single element', arr)

arr2d = np.array([[1, 2], [3, 4], [5, 6]])
arr2d = np.delete(arr2d, 1, axis=0)  
print('Deleting entire row',arr2d)

arr2d = np.delete(arr2d, 0, axis=1) 
print('Deleting entire column', arr2d)

Deleting only single element [10 30 40]
Deleting entire row [[1 2]
 [5 6]]
Deleting entire column [[2]
 [6]]
