### Scenario based question in Numpy

In [1]:
import numpy as np

[Student ID, Math Score, English Score, Science Score, Gender (0=Male, 1=Female), Age]


In [2]:
# Sample dataset
students = np.array([
    [101, 78, 85, 92, 0, 17],
    [102, 67, 76, 70, 1, 16],
    [103, 90, 88, 94, 0, 18],
    [104, 56, 64, 60, 1, 17],
    [105, 80, 70, 75, 0, 16],
    [106, 45, 50, 55, 1, 17],
    [107, 88, 90, 85, 0, 18],
    [108, 70, 60, 65, 1, 16],
    [109, 60, 75, 70, 0, 17],
    [110, 95, 92, 98, 1, 18]
])


#### 📋 Questions to Perform on This Dataset


In [3]:
# Find the average Math score.
average_of_math_score = np.mean(students[:, 1])
print('Average score of math',average_of_math_score)

Average score of math 72.9


In [4]:
# What is the maximum Science score?
max_score_in_science = np.max(students[:, 3])
print('Maximum score in science', max_score_in_science)

Maximum score in science 98


In [5]:
# Get the minimum English score for female students.
mask = students[:,4] == 1
female_students = students[mask]
print('Female students ', female_students)

min_score_female_english = min(female_students[:,2])
print('Female Students with minimum score ',min_score_female_english)

Female students  [[102  67  76  70   1  16]
 [104  56  64  60   1  17]
 [106  45  50  55   1  17]
 [108  70  60  65   1  16]
 [110  95  92  98   1  18]]
Female Students with minimum score  50


In [6]:
# Find the number of male and female students.
female_gender_mask = students[:,4]==1
male_gender_mask = students[:,4]==0

male_gender_count = sum(male_gender_mask)
female_gender_count = sum(female_gender_mask)

print("Number of Male Students:", male_gender_count)
print("Number of Female Students:", female_gender_count)

Number of Male Students: 5
Number of Female Students: 5


### Questions Filtering and Indexing

In [7]:
# Select all students who scored above 80 in Math.
above_80 = np.where(students[:, 1] > 80)
print('Students above than 80 ', students[above_80])

Students above than 80  [[103  90  88  94   0  18]
 [107  88  90  85   0  18]
 [110  95  92  98   1  18]]


In [8]:
# Get details of students aged 18.
aged_18 = np.where(students[:, -1] == 18)
print('Students age 18 ', students[aged_18])

Students age 18  [[103  90  88  94   0  18]
 [107  88  90  85   0  18]
 [110  95  92  98   1  18]]


In [9]:
# Find students with average score (Math+Eng+Sci)/3 > 85.
mean_of_students = np.where(np.mean(students[:, 1:4], axis=1) > 85)

print(students[mean_of_students])

[[103  90  88  94   0  18]
 [107  88  90  85   0  18]
 [110  95  92  98   1  18]]


### Advance question


In [10]:
# Add a new column with total score for each student.
total_score = np.sum(students[:, 1:4], axis=1)

add_new_column = np.column_stack((students,total_score))
print('Adding the new column into student ', add_new_column)

Adding the new column into student  [[101  78  85  92   0  17 255]
 [102  67  76  70   1  16 213]
 [103  90  88  94   0  18 272]
 [104  56  64  60   1  17 180]
 [105  80  70  75   0  16 225]
 [106  45  50  55   1  17 150]
 [107  88  90  85   0  18 263]
 [108  70  60  65   1  16 195]
 [109  60  75  70   0  17 205]
 [110  95  92  98   1  18 285]]


In [11]:
# Sort the dataset by total score descending.
total_scores = students[:, 1] + students[:, 2] + students[:, 3]

# Step 2: Get sorted indices in descending order of total score
sorted_indices = np.argsort(-total_scores)  # negative for descending

# Step 3: Sort the dataset using those indices
sorted_students = students[sorted_indices]

print("Sorted dataset by total score (descending):")
print(sorted_students)

Sorted dataset by total score (descending):
[[110  95  92  98   1  18]
 [103  90  88  94   0  18]
 [107  88  90  85   0  18]
 [101  78  85  92   0  17]
 [105  80  70  75   0  16]
 [102  67  76  70   1  16]
 [109  60  75  70   0  17]
 [108  70  60  65   1  16]
 [104  56  64  60   1  17]
 [106  45  50  55   1  17]]


In [12]:
average_score = np.mean(students[:, 1:4], axis=1)
pass_and_fail = np.where(average_score > 60, 'Pass', 'Fail')
pass_and_fail

array(['Pass', 'Pass', 'Pass', 'Fail', 'Pass', 'Fail', 'Pass', 'Pass',
       'Pass', 'Pass'], dtype='<U4')

### Manipulation

In [13]:
# Add a new student entry to the dataset.
new_student = np.array([117,34,56,78,0, 12])
all_students = np.vstack((students, new_student))
print(all_students)

[[101  78  85  92   0  17]
 [102  67  76  70   1  16]
 [103  90  88  94   0  18]
 [104  56  64  60   1  17]
 [105  80  70  75   0  16]
 [106  45  50  55   1  17]
 [107  88  90  85   0  18]
 [108  70  60  65   1  16]
 [109  60  75  70   0  17]
 [110  95  92  98   1  18]
 [117  34  56  78   0  12]]


In [14]:
# Delete the row for the student with ID = 106.
student_106 = np.where(students[:, 0] == 106)
deleted_student = np.delete(students, student_106, axis=0)
print(deleted_student)

[[101  78  85  92   0  17]
 [102  67  76  70   1  16]
 [103  90  88  94   0  18]
 [104  56  64  60   1  17]
 [105  80  70  75   0  16]
 [107  88  90  85   0  18]
 [108  70  60  65   1  16]
 [109  60  75  70   0  17]
 [110  95  92  98   1  18]]


In [15]:
# Extract only the Math and Science columns.
print(students[:, [1,3]])

[[78 92]
 [67 70]
 [90 94]
 [56 60]
 [80 75]
 [45 55]
 [88 85]
 [70 65]
 [60 70]
 [95 98]]


In [16]:
# Tranpose of students
print(students.T)

[[101 102 103 104 105 106 107 108 109 110]
 [ 78  67  90  56  80  45  88  70  60  95]
 [ 85  76  88  64  70  50  90  60  75  92]
 [ 92  70  94  60  75  55  85  65  70  98]
 [  0   1   0   1   0   1   0   1   0   1]
 [ 17  16  18  17  16  17  18  16  17  18]]
