### Scenario based question in Numpy

In [28]:
import numpy as np

[Student ID, Math Score, English Score, Science Score, Gender (0=Male, 1=Female), Age]


In [29]:
# Sample dataset
students = np.array([
    [101, 78, 85, 92, 0, 17],
    [102, 67, 76, 70, 1, 16],
    [103, 90, 88, 94, 0, 18],
    [104, 56, 64, 60, 1, 17],
    [105, 80, 70, 75, 0, 16],
    [106, 45, 50, 55, 1, 17],
    [107, 88, 90, 85, 0, 18],
    [108, 70, 60, 65, 1, 16],
    [109, 60, 75, 70, 0, 17],
    [110, 95, 92, 98, 1, 18]
])


#### 📋 Questions to Perform on This Dataset


In [30]:
# Find the average Math score.
average_of_math_score = np.mean(students[:, 1])
print('Average score of math',average_of_math_score)

Average score of math 72.9


In [31]:
# What is the maximum Science score?
max_score_in_science = np.max(students[:, 3])
print('Maximum score in science', max_score_in_science)

Maximum score in science 98


In [32]:
# Get the minimum English score for female students.
mask = students[:,4] == 1
female_students = students[mask]
print('Female students ', female_students)

min_score_female_english = min(female_students[:,2])
print('Female Students with minimum score ',min_score_female_english)

Female students  [[102  67  76  70   1  16]
 [104  56  64  60   1  17]
 [106  45  50  55   1  17]
 [108  70  60  65   1  16]
 [110  95  92  98   1  18]]
Female Students with minimum score  50


In [33]:
# Find the number of male and female students.
female_gender_mask = students[:,4]==1
male_gender_mask = students[:,4]==0

male_gender_count = sum(male_gender_mask)
female_gender_count = sum(female_gender_mask)

print("Number of Male Students:", male_gender_count)
print("Number of Female Students:", female_gender_count)

Number of Male Students: 5
Number of Female Students: 5


### Questions Filtering and Indexing

In [34]:
# Select all students who scored above 80 in Math.
above_80 = np.where(students[:, 1] > 80)
print('Students above than 80 ', students[above_80])

Students above than 80  [[103  90  88  94   0  18]
 [107  88  90  85   0  18]
 [110  95  92  98   1  18]]


In [35]:
# Get details of students aged 18.
aged_18 = np.where(students[:, -1] == 18)
print('Students age 18 ', students[aged_18])

Students age 18  [[103  90  88  94   0  18]
 [107  88  90  85   0  18]
 [110  95  92  98   1  18]]


In [36]:
# Find students with average score (Math+Eng+Sci)/3 > 85.
mean_of_students = np.where(np.mean(students[:, 1:4], axis=1) > 85)

print(students[mean_of_students])

[[103  90  88  94   0  18]
 [107  88  90  85   0  18]
 [110  95  92  98   1  18]]
