### Images in Numpy

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Save Numpy image format

In [5]:
zeros = np.zeros((3,4))
print(zeros)

# Save .npy image
np.save('Zeros.npy',zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Loading the Numpy Images

In [7]:
numpy_logo = np.load("Zeros.npy")
print(numpy_logo)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Show Numpy Image in Matplotlib